name: Python package

on: [push]

jobs:
  checks:
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, '3.10', 3.11]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade 'pip<23.0.0' 'setuptools<63.0.0'
        pip3 install -e .[dev]
        pip3 install coveralls
    - name: Code flake8 check
      run: |
        flake8
    - name: Doctest
      run: |
        python -m doctest numpy_ext.py
    - name: Test with pytest
      run: |
        pytest
        export COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}
        coveralls
